apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-2-app
    type: front-end
    env: production
spec:
  template:
    metadata:
      name: nginx-2
      labels:
        name: myapp
        env: production 
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
  replicas: 5
  selector:
    matchLabels:
      env: production
